# Generated by Django 4.2.3 on 2023-08-14 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_avant', models.ImageField(upload_to='images/')),
                ('image_apres', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('email', models.EmailField(blank=True, default='admin@admin.com', max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Dentiste', 'Dentiste'), ('Prothesiste', 'Prothesiste'), ('Admin', 'Admin')], default='Dentiste', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SharedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('cas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.cas')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.user')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('date_creation', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.user')),
            ],
        ),
        migrations.AddField(
            model_name='cas',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.patient'),
        ),
        migrations.AddField(
            model_name='cas',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_cas', to='myapp1.user'),
        ),
        migrations.AddField(
            model_name='cas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.user'),
        ),
    ]
